services:
  spotify_db:
    image: ghcr.io/kylemcginnis197/spotify_db:latest
    container_name: spotify_db
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - update_interval=3600
    volumes:
      - ./data:/app/data
      - ./.cache:/app/.cache